ACTIONS = ['IDLE', 'LEFT', 'RIGHT',  'JUMP_LEFT', 'JUMP_RIGHT']
REWARD_GOAL = 2500
REWARD_CHECKPOINT = 800
REWARD_DEFAULT = -0.1
REWARD_DEATH = -300
REWARD_FALL = -100
REWARD_COIN = 70


FILE_AGENT = 'robot_qtable.pkl'


RADAR_RANGE = 200
RADAR_RANGE_FLAG =1000
RADAR_RANGE_CHECKPOINT =600

EXPLORATION_RATE=0.7



