ACTIONS = ['IDLE', 'LEFT', 'RIGHT',  'JUMP_LEFT', 'JUMP_RIGHT']
REWARD_GOAL = 2500
REWARD_CHECKPOINT = 800
REWARD_DEFAULT = -0.1
REWARD_DEATH = -300
REWARD_FALL = -100
REWARD_COIN = 70


FILE_AGENT = 'robot_qtable.pkl'

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
WORLD_WIDTH = 3000

SCREEN_TITLE = "MR ROBOT Q-LEARNING"
CHARACTER_SCALING = 1
TILE_SCALING = 0.5
COIN_SCALING = 0.5

PLAYER_MOVEMENT_SPEED = 5
GRAVITY = 1
PLAYER_JUMP_SPEED = 20



